name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ github.repository }}:${{ github.sha }}
        post:
          - name: Set build status output
            run: echo "build_status=${{ job.status }}" >> $GITHUB_OUTPUT

  notif-discord:
      needs: build-and-push
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: send discord notification
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          args:  >
            **Docker Image CI**

            **Build and Push Status:** ${{ needs.build-and-push.outputs.build_status }}



# name: Push Docker Image 2

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   build-push:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile -t ${{ github.repository }} --tag ${{ github.repository }}:${{ github.sha }}
#     - name: Login to Docker Hub
#       run: docker login -u ${{ vars.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
#     - name: Push Docker image to Docker Hub
#       run: docker push ${{ github.repository }}:${{ github.sha }}